### ISSUE TITLE
Scripts do not make use of functions

### ISSUE THREAD

**Issue by ayushpriya10** [ayushpriya10/ShopKeepr#1]
Use functions to wrap around the code blocks and call them under later.

**Comment by SameeranB** [comment]
This issue has been resolved

**Comment by ayushpriya10** [comment]
sell.py and buy.py still do not make use of functions

**Comment by ayushpriya10** [comment]
Even database.py doesn't use functions.

**Comment by SameeranB** [comment]
Am I supposed to make everything functions?
